### ISSUE TITLE
Issue Loading Kernel

### ISSUE THREAD

**Issue by stownplayer** [yumiris/DietPi.Hyper-V#1]
I am testing this image out on Hyper-v but the image fails to boot. The error is below. Any ideas or is this image just not compatible on hyper v? I'm using the DietPi_Hyper-V-x86_64-Stretch - v6.25.3.vhdx by the way. 

"Loading Linux 4.9.0-8-AMD64
error: Invalid magic number
Loading initial ramdisk
error: you need to load the kernel first. "

Update - Tested the Virtualbox image and it works great. So I can use that if the hyper v won't work. Would be preferable however.

**Comment by yumiris** [comment]
Will give it a glance. In the meantime, mind providing me your VM configuration? The easiest way is to upload a screenshot of each configuration section for the VM.

**Comment by stownplayer** [comment]
https://ibb.co/MS1TQzh
https://ibb.co/82y8CLJ
https://ibb.co/GpZkdV8
https://ibb.co/hD7W0dr
https://ibb.co/hD8X315
https://ibb.co/yRtZLKV

**Comment by yumiris** [comment]
Hmm, nothing seems out of the ordinary.

I've created a quick VM on a completely fresh Windows 10 install, and I can't seem to be reproducing the issue:

![image](https://user-images.githubusercontent.com/10241434/62959900-1fa11680-be2c-11e9-93c9-63d3dbb31f64.png)

Can you confirm the checksum (or at least the file size in bytes) of the VHDX image? It could be a corrupted extraction. 🤔

---

For reference, here are the settings I've used for the VM:

|                                                                                                                |                                                                                                                |
| -------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------- |
| ![image](https://user-images.githubusercontent.com/10241434/62959562-ae616380-be2b-11e9-97dc-e77669c075be.png) | ![image](https://user-images.githubusercontent.com/10241434/62959571-b3beae00-be2b-11e9-843c-ab3454f4b2f0.png) |
| ![image](https://user-images.githubusercontent.com/10241434/62959584-b7eacb80-be2b-11e9-9660-0f208d1748e6.png) | ![image](https://user-images.githubusercontent.com/10241434/62959592-bfaa7000-be2b-11e9-9f3c-ca7dbc57ab1e.png) |

**Comment by stownplayer** [comment]
Well, the size matched exactly. However, I re-download and expanded the image. Copied back to the Hyper v server, deleted the vm, rebuilt it the same and it worked. I can't explain other than it must have been missing a bit somewhere lol. Looks good to me. Thanks for taking the time to look at it. I'm sorry to waste your time. I should have checked for image corruption.

**Comment by Hukuma1** [comment]
Is there any benefit of getting Gen2 support working? Selecting Gen2 fails to boot this DietPi image in Hyper-V for me.

**Comment by yumiris** [comment]
@Hukuma1, Gen 2 would use UEFI for booting instead of BIOS, though I can't think of any practical benefits for using UEFI when it comes to the context and scope of DietPi.

You do get goodies like GPT which give you more flexibility when it comes to filesystem partition layouts & sizes, though in my eyes, it'd be overkill for DietPi.

@MichaIng, perhaps you've got some ideas? 😛

**Comment by MichaIng** [comment]
Indeed UEFI is somehow useless for VMs, IMO, if not for testing/developing purpose only.

For this to work it would require a dedicated Hyper-V image created with DietPi-Imager as Clonezilla-based installer image. So you attach it as ROM drive, boot from there and install DietPi to the internal drive, just like one would do with Debian installers.

**Comment by Hukuma1** [comment]
Yeah no worries if there is no measurable improvement. I was just thinking Gen2 must somehow be better than Gen1. Because math. :D As long as Hyper-V continues to support it, this is a non-issue. Thanks guys!

**Comment by MichaIng** [comment]
But, hmm, is Gen2 really not MBR/BIOS-compatible? I see UEFI is supported, but couldn't find a clear hint that MBR/BIOS is not?
- https://docs.microsoft.com/en-gb/windows-server/virtualization/hyper-v/plan/should-i-create-a-generation-1-or-2-virtual-machine-in-hyper-v
