### ISSUE TITLE
Update to Buster-based image

### ISSUE THREAD

**Issue by MichaIng** [yumiris/DietPi.Hyper-V#2]
@yumiris 
If you find time, would you mind to create a new image based on new stable Debian Buster?
Includes many benefits, native PHP7.3, a much newer Linux (even 5.2 possible via backports) and of course generally better long term support.

But probably its best to wait for v6.26 stable release 😉.

**Comment by yumiris** [comment]
Release [v6.26.3](https://github.com/yumiris/DietPi.Hyper-V/releases/tag/v6.26.3) resorts to using an image made from scratch instead of branching off the VMware one. ^^
