### ISSUE TITLE
Default region on new install is GB?

### ISSUE THREAD

**Issue by Hukuma1** [yumiris/DietPi.Hyper-V#3]
Heya. Thanks so much for maintaining these, DietPi works great on my Win10 system.

Is there anyway to setup the region/keyboard settings based on IP when first booting into DietPi fresh? I recently found out it defaults to GB (I live in US) and had issues thinking my KB was malfunctioning because some keys were writing different things. ;)

**Comment by MichaIng** [comment]
@Hukuma1 
Yes, DietPi was born in GB, hence GB locales and keyboard layout is shipped by default :nerd_face:. But you can either switch it after/during firstrun setup via `dietpi-config` > `'5' ': Language/Regional Options'` or before first boot (e.g. after flashing the SDcard from host) by editing `dietpi.txt`, where you should find two settings accordingly.

Actually I want to switch the default locale to `C.UTF-8`, hence international default. But there is no such for the keyboard layout :thinking:, either it fits your keys, or not...

**Comment by Hukuma1** [comment]
Yeah that's what I do. Was just thinking if it were possible to auto check/set so users wouldn't be stuck where I was. But if not I guess we can just chalk this up to a 'noob user' issue. Either way, keep up the great work. My first Linux experience and love the minimalism/light-weight footprint of DietPi!

**Comment by MichaIng** [comment]
@Hukuma1 
What I can think of is to integrate keyboard layout into some first login setup prompt (wanted to do that anyway by times). All non-headless systems need to change it, if not by chance having a matching keyboard/region anyway.

**Comment by Hukuma1** [comment]
Even if it just runs dietpi-config 5 on first boot would be a big improvement.

**Comment by MichaIng** [comment]
@Hukuma1 
It runs DietPi-Software automatically with DietPi-Config link as second menu entry. However navigating through all entries is probably not what most users want to do on first login already. So IMO it is good to have a single first-login window with the most important options collected.
